package ru.sfedu.deals.enums;

public enum CliHBKeys {
  HB,

  HB_LAB1,
  HB_LAB2,
  HB_LAB3,
  HB_LAB4,
  HB_LAB5,

  /*lab_1*/
  GET_ALL_SCHEMAS,
  GET_SQL_HELP,
  GET_ALL_TABLES,
  GET_ALL_USERS,

  /*lab_2*/
  INSERT_TEST_ENTITY,
  GET_ALL_TEST_ENTITY,
  DELETE_TEST_ENTITY,
  UPDATE_TEST_ENTITY,

  /*lab_3*/
    /*joined table*/
  JT_INSERT_CREDIT_ACCOUNT,
  JT_SELECT_CREDIT_ACCOUNT,
  JT_DELETE_ACCOUNT,
  JT_UPDATE_ACCOUNT,
    /*mapped super class*/
  MSC_INSERT_CREDIT_ACCOUNT,
  MSC_SELECT_CREDIT_ACCOUNT,
  MSC_DELETE_ACCOUNT,
  MSC_UPDATE_ACCOUNT,
    /*single table*/
  ST_INSERT_CREDIT_ACCOUNT,
  ST_SELECT_CREDIT_ACCOUNT,
  ST_DELETE_ACCOUNT,
  ST_UPDATE_ACCOUNT,
    /*table per class*/
  TPC_INSERT_CREDIT_ACCOUNT,
  TPC_SELECT_CREDIT_ACCOUNT,
  TPC_DELETE_ACCOUNT,
  TPC_UPDATE_ACCOUNT,


  /*lab_4*/
    /*set*/
  SET_INSERT_USER,
  SET_SELECT_USER,
  SET_DELETE_USER,
  SET_UPDATE_USER,
    /*list*/
  LIST_INSERT_USER,
  LIST_SELECT_USER,
  LIST_DELETE_USER,
  LIST_UPDATE_USER,
    /*map*/
  MAP_INSERT_USER,
  MAP_SELECT_USER,
  MAP_DELETE_USER,
  MAP_UPDATE_USER,
    /*entity_set*/
  ESET_INSERT_USER,
  ESET_SELECT_USER,
  ESET_DELETE_USER,
  ESET_UPDATE_USER,
    /*entity_map*/
  EMAP_INSERT_USER,
  EMAP_SELECT_USER,
  EMAP_DELETE_USER,
  EMAP_UPDATE_USER,


  /*lab_5*/
  /*hql*/
    HQL_INSERT_USER,
    HQL_SELECT_USER,
    HQL_DELETE_USER,
    HQL_UPDATE_USER,
}
